language: go

go:
  - 1.5

before_install:
  - ./install-protobuf.sh

install:
  - go get -u google.golang.org/grpc
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway

before_script:
  - export PATH=$PATH:$HOME/protobuf
  - ./gen-proto.sh
