language: go

go:
  - 1.5

install:
  - go get -u google.golang.org/grpc
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway

before_script:
  - ./gen-proto.sh
