language: go

go:
  - 1.5.3

before_install:
  - ./install-protobuf.sh

install:
  - go get github.com/bradfitz/http2
  - go get github.com/gengo/grpc-gateway/protoc-gen-grpc-gateway
  - go get github.com/gengo/grpc-gateway/runtime
  - go get github.com/golang/glog
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get google.golang.org/grpc

before_script:
  - export PATH=$PATH:$HOME/protobuf
  - ./gen-proto.sh

script:
  # Enable only the tests we're debugging...
  - go test -v -run=TestHttpJson ./... --logtostderr --vmodule=util=3,*=1
