#!/bin/bash
SRC=$GOPATH/src
rm -Rf $SRC/google

echo "gateway go"
protoc \
  google/fakes/gateway.proto \
  -I . --go_out=plugins=grpc:$SRC

echo "protobuf go"
protoc \
  google/protobuf/*.proto \
  -I . --go_out=plugins=grpc:$GOPATH/src


echo "fix up the google3ism generated by protoc"
for sub in empty any duration field_mask timestamp
do
  mkdir $SRC/google/protobuf/$sub.pb
  mv $SRC/google/protobuf/$sub.pb.go $SRC/google/protobuf/$sub.pb
done

for sub in gateway
do
  mkdir $SRC/google/fakes/$sub.pb
  mv $SRC/google/fakes/$sub.pb.go $SRC/google/fakes/$sub.pb
done

echo "python"
rm -Rf python/google

protoc \
  google/fakes/gateway.proto \
  google/protobuf/*.proto \
  google/rpc/*.proto \
  google/api/http.proto \
  google/api/annotations.proto \
-I . --python_out=python --grpc_out=python \
  --plugin=protoc-gen-grpc=`which grpc_python_plugin`

echo "additional python package fixups"
touch python/google/__init__.py
touch python/google/api/__init__.py
touch python/google/rpc/__init__.py
touch python/google/protobuf/__init__.py
touch python/google/fakes/__init__.py

